### ISSUE TITLE
Custom media models with field widgets using CSS/JS media break in add/edit interfaces

### ISSUE THREAD

**Issue by kbayliss** [torchbox/wagtailmedia#1]
Hello,

I'm using a custom Media model:

```
from wagtailmedia.models import AbstractMedia, Media
from wagtail.wagtailcore.fields import RichTextField

class CustomMedia(AbstractMedia):
    transcript = RichTextField(blank=True)

    admin_form_fields = Media.admin_form_fields + (
        'transcript',
    )
```

Though when uploading or viewing a video/audio file, I get the following JS error: `makeHalloRichTextEditable is not defined`, and no Hallo bar appearing on the RichTextField. 

Any help would be appreciated!

**Setup:**
- wagtail==1.6.3
- wagtailmedia==0.1.1

Thanks,
Kyle

![audio](https://cloud.githubusercontent.com/assets/3009233/19444891/3e9e0f6c-948a-11e6-8485-28c02e40a2e8.png)
![video](https://cloud.githubusercontent.com/assets/3009233/19444892/3ec6feae-948a-11e6-9629-be011ad933c1.png)

**Comment by m1kola** [comment]
HI @kbayliss.

I haven't tried to extend `AbstractMedia` with `RichTextField`. Probably we need to add support of widget's media in add / edit interface. We need something [like this](https://github.com/torchbox/wagtail/blob/f432eca0b2346c38ed3136b241eb09c3d04ad0ff/wagtail/wagtailadmin/templates/wagtailadmin/pages/_editor_js.html#L35) for `wagtailmedia`.

BTW, I'm not sure that `RichTextField` will work if you try to extend Wagtail's `AbstractImage` or `AbstractDocument`. So there are to two possibilities to contribute an enhancements: into the wagtailmedia module and into Wagtail itself ;)

**Comment by thibaudcolas** [comment]
Yes, Wagtail has the same issue when extending images at least: https://github.com/wagtail/wagtail/issues/4466. @m1kola should this issue be closed in favour of the Wagtail one, or are they both useful?

**Comment by thenewguy** [comment]
Per https://github.com/wagtail/wagtail/issues/4466#issuecomment-522292360 this has now been fixed for images in Wagtail.  A solution could be modeled from this commit: https://github.com/wagtail/wagtail/commit/eaad01308142337739d7edd9f08bd8e714be23f0
