### ISSUE TITLE
Make use of thumbnail field for audio album cover

### ISSUE THREAD

**Issue by MechanisM** [torchbox/wagtailmedia#10]
[**Here**](https://github.com/torchbox/wagtailmedia/blob/master/wagtailmedia/forms.py#L29) `thumbnail` field has been removed for `audio` type, but I think that it is wrong. All `mp3`'s can have album covers in `ID3` tags, so I think it will be great to have album covers available in admin as well. When user uploads `audio` - album cover should be extracted from `mp3`, if it doesn't exists - user can upload cover, or just use some default cover with `wagtail` logo.
Same for `video`.. on upload - just calculate video size, dimentions, duration, and take a picture snapshot from video, and if needed user can upload their own one..
I'm planned to add support for reading/writing `ID3` tags for `wagtailmedia`, and  album covers for `audio` would be great advantage for this.
Also admin listing for `wagtailmedia` can be the same as for `wagtailimages` - just covers of videos and audios + their respective titles. And maybe even play/pause button on hover for `audio` and `video`

Also would be nice to have some additional fields like `artist` and `title` for both `audio` and `video`
Btw `formats` for `audio` and `video` files are important too - needed some fields to sort by `formats`. It is also important for for making queries for let's say - taking `avi` videos and converting them to `mp4` or for reading/writing tags and other manipulations, for stats as well.
Most of these things, I assume, can be done via custom media model, but at least keep thumbnail field for audio.

**Comment by MechanisM** [comment]
Btw, maybe just add some field like you did for StreamField and all media metadata would be just json?

**Comment by thenewguy** [comment]
Additional fields are easily added by custom media model and admin_form_fields.  I submitted PR that adds the thumbnail field back in for audio files
