### ISSUE TITLE
Exclude tests folder from wheels distribution

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/wagtailmedia#115]
### Issue Summary

#107 excludes the tests folder from our source distributions, but not from wheels, which are the most commonly used format. We need to find a way to exclude `tests` from both distributions. `packages=find_packages(exclude=["tests"])` doesn’t seem to work.

### Steps to Reproduce

```sh
python setup.py sdist bdist_wheel
```

**Comment by zerolab** [comment]
@thibaudcolas #137 solves that issue
