### ISSUE TITLE
Check form has field before accessing it

### ISSUE THREAD

**Issue by thenewguy** [torchbox/wagtailmedia#12]
Check that the field exists before deleting it at https://github.com/torchbox/wagtailmedia/blob/455c2926032de81e72aef4a93cdd325fb0aed7cd/wagtailmedia/forms.py#L27

For example, my custom media model sets video width and height automatically. So the width and height field are set to editable=False and excluded from the admin_form_fields.  This prevents the model form from working

**Comment by m1kola** [comment]
Thanks for the report. It makes sense.

Could you, please, submit a PR?

**Comment by thenewguy** [comment]
Submitted with tests

**Comment by m1kola** [comment]
Merged, thanks.

I'll try to upload a new version of the package to PyPI on Monday.

**Comment by m1kola** [comment]
[wagtailmedia==0.1.4](https://pypi.python.org/pypi/wagtailmedia/0.1.4) has been released.

@thenewguy, thanks for the PRs.
