### ISSUE TITLE
Migration 0003 Fails when getting Collections

### ISSUE THREAD

**Issue by joaquinstirling** [torchbox/wagtailmedia#128]
Hey how Is It Y'all ?

I've got this log when running a migrate after installing wagtailmedia.

![image_2021_02_26T13_57_50_669Z](https://user-images.githubusercontent.com/25124333/109310513-66463e00-7823-11eb-8065-5715de2f5032.png)

Anyone had a similar experience?

I hint It's something with the managers but Im unsure

**Comment by thenewguy** [comment]
This is the offending line. You have multiple root collections: https://github.com/torchbox/wagtailmedia/blob/master/wagtailmedia/migrations/0003_copy_media_permissions_to_collections.py#L26

Is this happening on a site with existing data?  Are your countdown_microsite migrations creating collections?  It should go away if you create them as a child of the root collection unless you need multiple root collections

**Comment by joaquinstirling** [comment]
Yes, I'm checking and every Collection there's is a root of themselves.

Yes the site has existing data.

No, the countdown_microsite migrations are not creating them. 

With what you said I started debugging and found that I'had a badly created Collection not being a child of Root collection, I'll make a migration to change that. I'll report here later on

**Comment by zerolab** [comment]
@joaquinstirling having not heard back in some time, I am going to close this.
If the issue is not related to the above, and is indeed specific to wagtailmedia and you are able to provide steps to reproduce will re-open happily!
