### ISSUE TITLE
Chooser tabs not working with Wagtail 2.13

### ISSUE THREAD

**Issue by zerolab** [torchbox/wagtailmedia#129]
from https://wagtailcms.slack.com/archives/C81FGJR2S/p1623162026405200

> When the "Choose a [model]" button is clicked, revealing the chooser modal, clicking on the non-active tabs (e.g. upload) fails to add the active class to the corresponding form elements, leaving them invisible.

**Comment by jams2** [comment]
Carrying over from slack - it looks like what's required is to add a `data-tab-nav` to the `ul` in the modal chooser template ( https://github.com/torchbox/wagtailmedia/blob/7ac143f1b4223097231653eb175fd459a432d729/wagtailmedia/templates/wagtailmedia/chooser/chooser.html#L9 ). I'll have a more thorough look and get a PR together.

**Comment by thibaudcolas** [comment]
It looks like this is fixed from #130 and v0.7.1 so I’ll close this now.
