### ISSUE TITLE
MediaChooserBlock doesn't show selected Media item

### ISSUE THREAD

**Issue by th3hamm0r** [torchbox/wagtailmedia#131]
### Issue Summary

Using `Media` in a `StreamField` (with a subclass of `AbstractMediaChooserBlock`) does not show the chosen media file.
I'm using the latest version of the package (0.7.1) and of wagtail (2.13.4).
I'm assuming this has something to do with the changes to the StreamField in wagtail 2.13?

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Integrate `wagtailmedia` as described in the current [README](https://github.com/torchbox/wagtailmedia/blob/e8fdaeea8528183d7a2f6e80e0169ee59e06a40e/README.md)
(some import statements in the example are not up-to-date)
3. Use the `HomePage` created by `wagtail start` to add media as a [regular django field](https://github.com/torchbox/wagtailmedia/blob/main/README.md#as-a-regular-django-field) and also [through a StreamField](https://github.com/torchbox/wagtailmedia/blob/main/README.md#in-streamfield).
4. Upload and choose a file with the chooser-field and the chooser-block, save.
5. After save/reload, the regular field will show the chosen file (allowing to clear choice, choose another item or edit the item), but the item selected through the chooser block remains in the state where you can choose a media item. Actually, the file is assigned, but the frontend just does not show this state.

### Technical details

* Python version: 3.8.10
* Django version: 3.2.5
* Wagtail version: 2.13.4
* `wagtailmedia` version: 0.7.1
* Browser version: FireFox 89

**Comment by ephes** [comment]
I can confirm it still works up to wagtail 2.12.6.

**Comment by ephes** [comment]
Did a small [PR](https://github.com/torchbox/wagtailmedia/pull/136).

**Comment by zerolab** [comment]
Fixed in #136. Will be release soon
