### ISSUE TITLE
Support wagtail "headless" (v2 API)

### ISSUE THREAD

**Issue by ruilvo** [torchbox/wagtailmedia#146]
### Issue Summary

As [per the docs](https://docs.wagtail.io/en/stable/advanced_topics/api/v2/configuration.html), it's easily possible to get API endpoints for the built-in document types.

Example:

```python
from wagtail.api.v2.router import WagtailAPIRouter
from wagtail.images.api.v2.views import ImagesAPIViewSet

api_router = WagtailAPIRouter("wagtailapi")

api_router.register_endpoint("images", ImagesAPIViewSet)
```

### Steps to Reproduce

N/A

### Expected behaviour

For there to exist `MediaAPIViewSet` in `wagtailmedia.api.v2.views`.

### Technical details

* Python version: Python 3.9.9
* Django version: Version: 3.2.10
* Wagtail version: Version: 2.15.1
* `wagtailmedia` version: Version: 0.8.0
* Browser version: Firefox 95

**Comment by zerolab** [comment]
@ruilvo thank you for the suggestion. A PR would very welcome too

**Comment by hallpower** [comment]
[Archive.zip](https://github.com/torchbox/wagtailmedia/files/8084203/Archive.zip)

Added support for api/v2. Thought I'd share, even though not a PR.
