### ISSUE TITLE
Please just include `python manage.py collectstatic` in docs

### ISSUE THREAD

**Issue by G-kodes** [torchbox/wagtailmedia#149]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

You don't mention that there are static asset files (`*-model.js`) that provide the modal selector functionality in the Wagtail Admin interface. It took me a couple of days to figure out that the reason my admin interface `StreamField` rendered a blank section was because I had not run `python manage.py collectstatic`.

Can we just add that in the documentation/README? I know its a small detail but it definitely made a difference in my case XD

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Integrate `wagtailmedia` as per documentation (minus collect static command)
3. Try and create page with `StreamField` `VideoChooserBlock`

**Comment by zerolab** [comment]
note added in 2f0feda, thanks @G-kodes
