### ISSUE TITLE
jQuery-File-Upload for video and audio

### ISSUE THREAD

**Issue by thenewguy** [torchbox/wagtailmedia#15]
I was briefly looking over how wagtailimages uploads.  

The uploader it uses supports audio and video previews too:
- https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload-audio.js
- https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload-video.js

Any idea how well it works?  Any plans for integration?

**Comment by m1kola** [comment]
I can't say that wagtailmedia is under active development, but I will be happy to review and merge a pull request for this, if you prepare a solution.

**Comment by thenewguy** [comment]
@m1kola Can you expand at all on the "future" of wagtailmedia?

**Comment by thenewguy** [comment]
Closed in favor of https://github.com/torchbox/wagtailmedia/issues/81
