### ISSUE TITLE
Using 'media_type' option for MediaChooserPanel results in error

### ISSUE THREAD

**Issue by ababic** [torchbox/wagtailmedia#152]
### Issue Summary

Using the `media_type` argument of `wagtailmedia.edit_handlers.MediaChooserPanel` causes an error to be raised when I view the edit page for the model I used it on. When I remove the `media_type` argument, it works fine.

### Technical details

* Python version: 3.8.12
* Django version: 3.2.11
* Wagtail version: 2.15.2
* `wagtailmedia` version: 0.7.1

### Stack trace

```
File "models.py", line 67, in get_content_panels
    MediaChooserPanel("media", media_type="audio")
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/edit_handlers.py", line 454, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'media_type'
```

**Comment by ababic** [comment]
Ah, bloody heck. As soon as I submitted this, I realised I'm not on the latest version, and changing that solves the problem! Sorry for the noise :(

**Comment by zerolab** [comment]
No problem at all! Love the self-resolving issues ;)
