### ISSUE TITLE
"Error: port is undefined" in Firefox console at video playback

### ISSUE THREAD

**Issue by krzysztofjeziorny** [torchbox/wagtailmedia#153]
### Issue Summary

An mp4 video (h.264, 1080p) posted in a streamfield creates constant error "port is undefined" in the Console window of Firefox at the video playback.

<img width="487" alt="Screenshot 2022-03-21 at 12 26 35" src="https://user-images.githubusercontent.com/872730/159252647-1c97bfee-f827-4d06-bd51-1da4cb3fb442.png">

### Steps to Reproduce

1. post a video file
2. Integrate `wagtailmedia` in a [StreamField](https://github.com/torchbox/wagtailmedia#in-streamfield) (code same as in the project's readme example)
3. play the video in Firefox - the playback goes fine, but the error is re-created when the file is streaming

It doesn't happen in latest Safari or Chromium at all. There is also no javascript interacting with the media file.

Can't yet post a link to the file in question (will do when the content is published). Did someone see anything like this? Maybe my video file is encoded in a wrong way? Or is it purely a Firefox bug I can/must ignore for now?
Thank you for any hints.

### Technical details

* Python version: 3.9.2
* Django version: 3.2.12
* Wagtail version: 2.16.1
* `wagtailmedia` version: 0.9.0 
* Browser version: Firefox 98.0.1 MacOS

**Comment by zerolab** [comment]
@krzysztofjeziorny where does that error originate from? (click on "undefined" to get the full thing)
Do you use any kind of library for the video playback on the front-end?

**Comment by krzysztofjeziorny** [comment]
@zerolab 'undefined' is not linked. There is no library, just a `video` tag as from the documentation.

Firefox 98 on Debian 11 describes the error as: `Error: Attempt to postMessage on disconnected port`. It doesn't say more unfortunately.

**Comment by krzysztofjeziorny** [comment]
My suspicion is the error comes from some Firefox extension and demonstrates weirdly only at the playback. Pure Firefox Developer Edition sees none of this, so apologies, closing it now.
