### ISSUE TITLE
Attribute error with plain custom media model

### ISSUE THREAD

**Issue by tbrlpld** [torchbox/wagtailmedia#160]
### Issue Summary

When setting wagtailmedia up with custom media model I and click the "add video" button, I get the following error:
`type object 'CustomMedia' has no attribute 'admin_form_fields'`

### Steps to Reproduce

* Setup wagtailmedia in a Wagtail project
* Configure a plain custom media model like this:
    ```
    from wagtailmedia import models as media_models


    class CustomMedia(media_models.AbstractMedia):
        pass
    ```
* Open the Wagtail admin
* Navigate to the "media" screen
* Click the "add video" button

To fix this issue I need to use:

```
class CustomMedia(media_models.AbstractMedia):
    admin_form_fields = media_models.Media.admin_form_fields

```

I wonder if the fields should be added to the `AbstractMedia` model, or if we should update the instructions in the README to work with a custom media model. 

### Technical details

* Python version: 3.9.13
* Django version: 4.0.4
* Wagtail version: 2.16.2
* `wagtailmedia` version: 0.9.0
* Browser version: You can use http://www.whatsmybrowser.org/ to find this out.

**Comment by zerolab** [comment]
@tbrlpld sorted in #161
