### ISSUE TITLE
ModuleNotFoundError: No module named 'wagtailmedia'

### ISSUE THREAD

**Issue by balasbk** [torchbox/wagtailmedia#164]
Found an issue? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue.

### Steps to Reproduce

1. After installing wagtailmedia . when I try to run manage.py migrate. it's showing this error (ModuleNotFoundError: No module named 'wagtailmedia')

### Technical details

* Python version: 3.9
* Django version: 3.2.13
* Wagtail version: 2.14.2
* `wagtailmedia` version: 0.9.0

**Comment by zerolab** [comment]
Can you please add the full traceback?

**Comment by balasbk** [comment]
solved the issue I have 2 versions of python, so delete one now it's working fine
