### ISSUE TITLE
Wagtail 4.0 UI Issues

### ISSUE THREAD

**Issue by th3hamm0r** [torchbox/wagtailmedia#167]
### Issue Summary

Everything works basically, but I have found some obvious UI issues:

1. Text-size on wagtail's dashboard:
![wagtailmedia_wagtail_home_issue](https://user-images.githubusercontent.com/468164/185061379-e1462e96-5f04-4717-80fd-87fa82c1eed7.png)

2. The list view's header looks partially unstyled:
![wagtailmedia_listview_header](https://user-images.githubusercontent.com/468164/185061775-1e2c6b61-9252-4670-b1db-6b3c8f7d13cd.png)
compared to images:
![wagtail_images_listview](https://user-images.githubusercontent.com/468164/185061861-d7696c94-77b4-44f0-b170-ac429275d593.png)

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Integrate `wagtailmedia`

### Technical details

* Python version: 3.10
* Django version: 4.1
* Wagtail version: 4.0rc1
* `wagtailmedia` version: 0.10.1
* Browser version: Firefox 103

**Comment by zerolab** [comment]
Thank you @th3hamm0r, I will have some time on Friday to go over this.
There are also some [test failures](https://github.com/torchbox/wagtailmedia/runs/7830171784?check_suite_focus=true#step:6:121) to sort out

**Comment by zerolab** [comment]
@th3hamm0r I opened #169 to solve this and tidy up other templates. Would be great if you could take it for a test 🙏

**Comment by th3hamm0r** [comment]
@zerolab great news, thx! I will test it on monday
