### ISSUE TITLE
Expected UI issues with Wagtail 4.0 release

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/wagtailmedia#173]
Follow-up to #167. This is similar to #157, which we opened for Wagtail 3.0.

Via code search, I detected one potential issue in wagtailmedia, with the chooser upload form’s error handling:

https://github.com/torchbox/wagtailmedia/blob/f699c57e738d50397347e12dfcf3c37917abccb3/src/wagtailmedia/static/wagtailmedia/js/media-chooser-modal.js#L78-L82

This relies on field markup which is no longer present in Wagtail 4.0 (`field-content` class). Here is updated error handling in Wagtail’s core choosers: https://github.com/wagtail/wagtail/blob/fc95605c8221cf8849e4a9fd424ce84121137fa1/client/src/includes/chooserModal.js#L9

The necessary change here is to inject the field errors in the right place in the new markup, with the expected ARIA attributes.

I would expect a change like this (pseudo code, untested):

```diff
+ const input = $('#id_title', modal.body).get(0);
+ 
-if ($('#id_title', modal.body).val() == '') {
+if (!input.value) {
-    var li = $('#id_title', modal.body).closest('li');
-    if (!li.hasClass('error')) {
+    if (!input.hasAttribute('aria-invalid')) {
-        li.addClass('error');
-        $('#id_title', modal.body).closest('.field-content').append('<p class="error-message"><span>This field is required.</span></p>')
+        input.setAttribute('aria-invalid', 'true');
+        const field = input.closest('[data-field]');
+        field.classList.add('w-field--error');
+        const errors = field.querySelector('[data-field-errors]');
+        const icon = errors.querySelector('.icon');
+        if (icon) {
+            icon.removeAttribute('hidden');
+        }
+        const errorElement = document.createElement('p');
+        errorElement.classList.add('error-message');
+        errorElement.innerHTML = gettext('This field is required.');
+        errors.appendChild(errorElement);
    }
    setTimeout(cancelSpinner, 500);
} else {
```

---

There are additionally two other potential issues detected, but they are flagging legacy markup in legacy templates so very likely false positives: usage of `human-readable-date`, and `field-small iconfield`

```
wagtail/torchbox/wagtailmedia/src/wagtailmedia/templates/wagtailmedia/media/legacy/index.html
35: {% include "wagtailadmin/shared/field_as_li.html" with field=field field_classes="field-small iconfield" input_classes="icon-search" %}

wagtail/torchbox/wagtailmedia/src/wagtailmedia/templates/wagtailmedia/media/legacy/list.html
58:                <td><div class="human-readable-date" title="{{ media_file.created_at|date:"d M Y H:i" }}">{{ media_file.created_at|timesince }} ago</div></td
```

**Comment by zerolab** [comment]
The legacy templates are loaded for Wagtail < 4.0, so should not be an issue.

Will have a look at the error bit. Didn't come up in #169
