### ISSUE TITLE
Chooser buttons not visible on hover with wagtail 4.0.2

### ISSUE THREAD

**Issue by th3hamm0r** [torchbox/wagtailmedia#175]
### Issue Summary

This has worked with wagtail 4.0.1:
![wagtailmedia_chooser_wagtail4 0 2](https://user-images.githubusercontent.com/468164/192276967-7c8da8c7-82e8-4a2a-8233-d1742f3a4112.gif)

Related: #173

### Steps to Reproduce

1. Start the interactive test with `tox -re interactive` ("-r" to clear any existing venv with an old wagtail)
2. Login and go to http://0.0.0.0:8020/admin/pages/add/wagtailmedia_tests/eventpage/2/
3. Add a related media and then find those invisible buttons

### Technical details

* Python version: 3.10
* Django version: 4.1.1 (tox interactive), 3.2 (actual deployment)
* Wagtail version: 4.0.2
* `wagtailmedia` version: 0.11
* Browser version: Firefox 105

**Comment by zerolab** [comment]
Uff, I wonder what changed.
Note to self: #172 addressed a similar thing before

**Comment by th3hamm0r** [comment]
@zerolab sry, didn't have the time to search for the reason initially, but now I've tried a bit and it seems like this change https://github.com/wagtail/wagtail/commit/44d954e00a6f894eb6951f9fcbb9285a0bf1946b could be the cause.
I've also found the issue for custom choosers based on the new helper classes in wagtail 4.
I will open an issue there.

**Comment by zerolab** [comment]
Fixed in e7b333f

**Comment by th3hamm0r** [comment]
Thx for the fix, but actually it shouldn't be necessary to fix it for every custom chooser (like for wagtailmedia), I think it should be fixed in wagtail: https://github.com/wagtail/wagtail/issues/9260

**Comment by zerolab** [comment]
I know, this is a case where I don't want to wait for core.
will remove once that if fixed by doing another patch release
