### ISSUE TITLE
UI issues with wagtail 4.1

### ISSUE THREAD

**Issue by th3hamm0r** [torchbox/wagtailmedia#183]
### Issue Summary

Found two minor issues with wagtail 4.1rc1, which are not present with 4.0:
1. ~~The add button (dropdown) on the media's listing seems to be bigger now, but the second item (add video) seems to use the old size (?):~~ **edit:** I've created an issue in wagtail core: https://github.com/wagtail/wagtail/issues/9476
![wagtailmedia_add_button_sizes](https://user-images.githubusercontent.com/468164/197486441-48dded32-280f-47f4-bf7c-39c64315b2a4.png)
2. Misplaced loading spinner on the create audio/video screen :
![wagtailmedia_upload_spinner](https://user-images.githubusercontent.com/468164/197477448-a6319425-7b4c-40b8-8b91-1c6c91c86c5a.gif)

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Integrate `wagtailmedia`
3. Login to CMS, go to media.
3.1. Look at the create-button on the top right
3.2. go to the create-new-audio/-video-screen, click on the save button

### Technical details

* Python version: 3.10
* Django version: 3.2
* Wagtail version: 4.1rc1
* `wagtailmedia` version: 0.11.1
* Browser version: Firefox 106

**Comment by zerolab** [comment]
Does the same happen with other interfaces (e.g. a report) that have the header action dropdown?

**Comment by th3hamm0r** [comment]
Good point, those views also have the issue with the dropdown. So it's actually a wagtail core issue, sry...

The submit button's spinner issue still seems to be an issue with wagtailmedia, because the site report also has one, which does not have this issue.

**Comment by zerolab** [comment]
Would be OK to open a core issue for those dropdowns? Would be nice to fix before 4.1 goes out

**Comment by th3hamm0r** [comment]
Yes! Are you opening one? I'm not sure if that was a question for me, to open one or if I'm ok, which I'm of course :smile:
Fyi: I've also checked the styleguide-app, basically all styled dropdown buttons have those minor size/padding issues.

**Comment by zerolab** [comment]
Sorry, I did mean "would you be ok" :D

**Comment by zerolab** [comment]
Alright, will close this in favour of https://github.com/wagtail/wagtail/issues/9476
Thank you @th3hamm0r

**Comment by th3hamm0r** [comment]
@zerolab the second issue, concerning the misplaced spinner, is still unsolved?
