### ISSUE TITLE
render_basic() bug in Readme

### ISSUE THREAD

**Issue by veuncent** [torchbox/wagtailmedia#19]
In the example in the Readme of this project, `render_basic()` is called without the `context` argument. 
This causes the error `render_basic() got an unexpected keyword argument 'context'`.

Should be `def render_basic(self, value, context=None):`

This is already explained in the docs: http://docs.wagtail.io/en/v1.13/releases/1.6.html#render-and-render-basic-methods-on-streamfield-blocks-now-accept-a-context-keyword-argument 

See also: https://stackoverflow.com/questions/42419382/wagtail-comparing-revisions-produces-render-got-an-unexpected-keyword-argume

**Comment by nimasmi** [comment]
Thanks for reporting @veuncent!
