### ISSUE TITLE
 When publishing the page, MediaBlock does not report an error when it does not fill in anything

### ISSUE THREAD

**Issue by tangwenhao** [torchbox/wagtailmedia#206]
When publishing the page, select MediaBlock to upload the video. In the upload video tab, select nothing, click the upload button directly, and the code will jump out directly, and it cannot be friendly to prompt that no content has been entered.

**Comment by zerolab** [comment]
Would appreciate a short screen recording of this happening, ideally with the browser developer console open to see whether there are any JS errors

**Comment by tangwenhao** [comment]
> Thank you for the report. I'd appreciate a short screen recording of this happening, ideally with the browser developer console open to see whether there are any JS errors



> Thank you for the report. I'd appreciate a short screen recording of this happening, ideally with the browser developer console open to see whether there are any JS errors

![pic1](https://github.com/torchbox/wagtailmedia/assets/7843826/b5a1fbc5-b504-4a1c-b497-1ae6f0ea7e44)

![pic2](https://github.com/torchbox/wagtailmedia/assets/7843826/3d4f794d-ecb9-411f-8483-7c630eddf66e)

**Comment by zerolab** [comment]
Sorry for the delay in responding to this.
I seems this may be an issue coming from Wagtail itself: https://github.com/wagtail/wagtail/issues/10498
