### ISSUE TITLE
AudioChooserBlock edit button href is empty

### ISSUE THREAD

**Issue by marts** [torchbox/wagtailmedia#207]
### Issue Summary

On an upgrade from wagtailmedia 0.12.0 to 0.14.1 I noticed the 'Edit this audio item' button on the AudioChooserBlock was not linking to the media item (in this case an audio file).

This works fine for 0.12.0 and 0.13.0, but not 0.14.0 and 0.14.1

### Steps to Reproduce

1. Create a struct block with an AudioChooserBlock
2. Select an audio file
3. Try to edit the audio file using the 'Edit this audio item' button

<img width="1117" alt="Screenshot 2023-06-08 at 14 39 15" src="https://github.com/torchbox/wagtailmedia/assets/1315296/c47442e0-2a9c-447a-90c4-e62939057556">

### Technical details

* Python version: 3.11
* Django version: 4.1.7
* Wagtail version: 4.1.3
* `wagtailmedia` version: 0.14.1
* Browser version: Firefox 113

**Comment by zerolab** [comment]
https://github.com/torchbox/wagtailmedia/releases/tag/v0.14.2
