### ISSUE TITLE
Use tag widget in popup chooser

### ISSUE THREAD

**Issue by harrislapiroff** [torchbox/wagtailmedia#214]
### Issue Summary

The media upload form in the media section of the admin has an autocompleting tokenizing tag widget but the form in the popup has a plain text field:

In popup:
![image](https://github.com/torchbox/wagtailmedia/assets/296631/61ae08d2-3660-43f8-93c9-0850ad3294b4)

In media section of admin:
![image](https://github.com/torchbox/wagtailmedia/assets/296631/0185c4c6-f9ae-4e8a-a035-c83bcc26b758)

This can produce some user confusion: we had an admin complain that when they pressed "enter" to confirm a tag, it submitted the form instead and as you can see above, I wasn't sure whether tags should be space-separated or comma-separated in the popup. (In retrospect the help text does say to use quotes, but it's not the clearest help text I've seen and better would be to unify the two interfaces).

### Steps to Reproduce

1. Edit a page that uses `MediaChooserBlock`
2. Add a media block and click "choose media item"
3. Choose "Upload video" (interestingly the behavior is fine for "Upload audio")
4. Try to enter multiple tags using [tag name] + enter button

Expected behavior is that it would complete the tag token and allow me to enter another tag. Actual behavior is that it submits the form.

### Technical details

* Python version: 3.9.16
* Django version: 3.2.20
* Wagtail version: 4.1.4
* `wagtailmedia` version: 0.14.2
* Browser version: Firefox 115 macOS 10.15

**Comment by zerolab** [comment]
Hey @harrislapiroff, this should be fixed in v0.14.3
