### ISSUE TITLE
Change `insert_editor_css` to `insert_global_admin_css`

### ISSUE THREAD

**Issue by jamesbiggs** [torchbox/wagtailmedia#217]
### Issue Summary

When upgrading to `wagtail` 5.1 and upgrading `wagtailmedia` to 0.14.3, I get a `RemovedInWagtail60Warning` for the `insert_editor_css`, telling me it'll be removed in wagtail 6.0, which comes from:

https://github.com/torchbox/wagtailmedia/blob/a469ce23201c2f00975501b1ba3020bed0ab6fab/src/wagtailmedia/wagtail_hooks.py#L112

### Steps to Reproduce

1. Upgrade to `wagtail` 5.1
2. Upgrade to `wagtailmedia` 0.14.3
3. See that you get a deprecation warning

### Technical details

* Python version: 3.11.4
* Django version: 4.2.3
* Wagtail version: 5.1
* `wagtailmedia` version: 0.14.3
* Browser version: Chrome 115

**Comment by zerolab** [comment]
Fixed via #218
