### ISSUE TITLE
Option to upload a media file on chooser field

### ISSUE THREAD

**Issue by kaduuuken** [torchbox/wagtailmedia#22]
It would be very helpful, if I could upload a file directly while editing a page within the ChooserField, just like with Image and File, where there are two tabs named "Search" and "Upload".

**Comment by thibaudcolas** [comment]
Looks like #66 implements this.

**Comment by thibaudcolas** [comment]
Thank you to @teixas for implementing this in #97 :) This will be released soon in v0.6.0.

![upload](https://user-images.githubusercontent.com/877585/90258199-17fdbe80-de40-11ea-80cd-34b238d137c7.gif)
