### ISSUE TITLE
`classnames` Deprecation Warning

### ISSUE THREAD

**Issue by jamesbiggs** [torchbox/wagtailmedia#224]
### Issue Summary

When upgrading to `wagtail` 5.2, I get a `RemovedInWagtail60Warning` for the `classnames` attribute, telling me it'll be removed in `wagtail` 6.0, which comes from:

https://github.com/torchbox/wagtailmedia/blob/0573ddc9050e4adfb415cccdb725f19c1f63c3ea/src/wagtailmedia/wagtail_hooks.py#L73-L81

### Steps to Reproduce

1. Upgrade to `wagtail` 5.2
2. See that you get a deprecation warning in the logs

### Technical details

* Python version: 3.11.6
* Django version: 4.2.7
* Wagtail version: 5.2
* `wagtailmedia` version: 0.14.4
* Browser version: Chrome 118

**Comment by zerolab** [comment]
fixed via accd29a
