### ISSUE TITLE
`from wagtailmedia.forms import MediaForm` causes `django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.`

### ISSUE THREAD

**Issue by ordigital** [torchbox/wagtailmedia#241]
I have a problem with imports. 

I have custom image model in `portal/models/media/image.py` and it's imported through `portal/models.py` so I can use `WAGTAILIMAGES_IMAGE_MODEL = 'portal.ImageModel'` in `base.py`. This works without any problems.

But when I try to do custom model for `wagtailimages` and I have a media model in `portal/models/media/media.py` imported same way through `portal/models.py` it shows exception: `django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.` that is thrown because of those two imports in `media.py`: `from wagtailmedia.models import AbstractMedia` and `from wagtailmedia.forms import MediaForm`. Why is that?

In `image.py` I have imports: `from wagtail.images.models import Image as WagtailImage` and `from wagtail.images.models import AbstractImage, AbstractRendition` but they are not causing this error.

I've tried to change order of `wagtailmedia` and my `portal` app in `INSTALLES_APPS` but nothing changes. 
How to deal with it to make it work?

**Comment by zerolab** [comment]
Can you provide the full traceback, please?

**Comment by ordigital** [comment]
```python
from django import forms
from django.db import models

from wagtailmedia.models import AbstractMedia
#from wagtailmedia.forms import MediaForm <-- this causes an exception: django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

class MediaModel(AbstractMedia):
    description = models.CharField(max_length=255, blank=True, verbose_name='Opis') # <- this filed is not added to form

# class MediaModelForm(MediaForm):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         instance = kwargs.get('instance')
#         if instance and 'video' in instance.file_mimetype:
#             #self.fields['custom_field'] = forms.CharField(max_length=255)
#             pass
#         elif instance and 'audio' in instance.file_mimetype:
#             #self.fields['custom_field'] = forms.CharField(max_length=255)
#             pass
```

**Comment by zerolab** [comment]
Looking at your code and traceback, the issue is with the fact you define the model, and the form in the same module and there's a bit of a dependency there. I suggest moving your `MediaModelForm` definition in `portal/forms.py` or `portal/forms/media.py` and update the `MEDIA_FORM_BASE` setting to reflect the change

**Comment by ordigital** [comment]
Yes, I've just figured out that while it is necessary for `MediaModel(AbstractMedia)`  to be imported in `models.py` or `__init__` in `models` folder, it causes an exception in case of  `MediaModelForm(BaseMediaForm)` which should not be loaded automatically with app. 

But now I am quite confused because while adding fields in `MediaModelForm(BaseMediaForm)` works, it doesn't work in `MediaModelForm(BaseMediaForm)`. 

This works:
```python
from django import forms
from wagtailmedia.forms import BaseMediaForm

class MediaModelForm(BaseMediaForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance and instance.type == 'audio':
            self.fields['custom_field'] = forms.CharField(max_length=255,label="Test audio")
     
        else:
            self.fields['aaaa_field'] = forms.CharField(max_length=255,label="Test video")
            
```

but this does nothing:

```python
class MediaModel(AbstractMedia):
    description = models.CharField(max_length=255, blank=True) # <- this filed is not added to form
```

**Comment by ordigital** [comment]
This seems to do do trick but I don't know why it's not in the docs…

```python
class MediaModel(AbstractMedia):
    test = models.CharField(max_length=255, verbose_name="AAAA", blank=True)

    admin_form_fields = (
        "title",
        "file",
        "collection",
        "duration",
        "width",
        "height",
        "thumbnail",
        "tags",
        "test",  # <-- added field
    )
```

**Comment by zerolab** [comment]
@ordigital feel free to submit a PR improving the docs.
It is difficult to cover everything and, as a maintainer, there's a certain ingrained knowledge that can feel like "but everyone knows this"

**Comment by ordigital** [comment]
I see now that's analogous to custom image and custom document model and it's quite easy to look up. Anyway thanks for help – problem solved. :)

**Comment by zerolab** [comment]
Glad to hear. Will mark this as closed, then
