### ISSUE TITLE
0.15.2 release notes should mention new minimum versions

### ISSUE THREAD

**Issue by Scotchester** [torchbox/wagtailmedia#247]
Version 0.15.2 included a [change to the minimum supported versions of Wagtail and Django](https://github.com/torchbox/wagtailmedia/commit/3b0c3e1b26485b718c17923c4cb9d2081ad0e10e#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711). It would be nice if the notes for this release could be updated to mention that :)

**Comment by Scotchester** [comment]
Also just realized the README doesn't mention supported versions at all.

**Comment by zerolab** [comment]
Thanks @Scotchester updated https://github.com/torchbox/wagtailmedia/releases/tag/v0.15.2

**Comment by zerolab** [comment]
And README - https://github.com/torchbox/wagtailmedia?tab=readme-ov-file#requirements

**Comment by Scotchester** [comment]
Thank you @zerolab! 💚
