### ISSUE TITLE
Upload buttons doesn't have any styles

### ISSUE THREAD

**Issue by MechanisM** [torchbox/wagtailmedia#3]
Seems like button for uploading media missing proper classes, and looks unstyled, and btw it always show uploading with spinner, even when not doing any uploads.

**Comment by m1kola** [comment]
Could you, please, specify which version of Wagtail you use?

**Comment by MechanisM** [comment]
The latest one, from master, cloned it and `pip install -e .`

**Comment by m1kola** [comment]
I suspect button looks unstyled because this module was originally developed for Wagtail 1.4. Then in Wagtail 1.5 were made some changes in front-end.

Potential solution is described [here](http://docs.wagtail.io/en/v1.7/releases/1.5.html#buttons-in-admin-now-require-class-button).
