### ISSUE TITLE
Updating for wagtails 2

### ISSUE THREAD

**Issue by sewagodimo** [torchbox/wagtailmedia#32]
> Django 1.6 is long gone now, and so we've taken the 2.0 release as an opportunity to drop the 'wagtail' prefix - see the 2.0 release notes for the complete list of renamed modules. The wagtail updatemodulepaths command can be used to automatically convert all module references across your project:
> 
> wagtail updatemodulepaths (run from the root of your project) will immediately update your project files in place
> wagtail updatemodulepaths --list and wagtail updatemodulepaths --diff will show a preview of the changes to be made

The current wagtailmedia is not updated for the correct imports and it is giving me errors

**Comment by tomdyson** [comment]
Hey @sewagodimo, this has been worked on at https://github.com/torchbox/wagtailmedia/pull/26 - if you can test that branch and update the PR with any comments, that'd be very helpful. Thanks!
