### ISSUE TITLE
Make wagtailmedia compatible with Wagtail 2

### ISSUE THREAD

**Issue by codiebeulaine** [torchbox/wagtailmedia#33]

**Comment by zerolab** [comment]
#26 is now merged and is part of v0.2.0

**Comment by thibaudcolas** [comment]
@zerolab should this issue be closed?

**Comment by zerolab** [comment]
Yes

**Comment by thibaudcolas** [comment]
@m1kola @nimasmi @kaedroho could one of you give @zerolab and I some rights over this repository so we can do this type of triage?

**Comment by nimasmi** [comment]
@zerolab and @thibaudcolas are now admins.
