### ISSUE TITLE
Wrong file permission when loading mp4

### ISSUE THREAD

**Issue by BronzeCrab** [torchbox/wagtailmedia#35]
Im using 0.2 version, If i upload mp3 media file then its ok and It has permission: `-rw-r--r--` and i can use it. But If i upload mp4 video then it has `-rw-------` and because of that i cant use it on my site. When i change video permissions to `-rw-r--r--` then it fix it. Thanks.

**Comment by thenewguy** [comment]
Going to close this issue.  Reopen if there is something this project should do to help here
