### ISSUE TITLE
Add demo project to the repository for manual testing

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/wagtailmedia#48]
To meaningfully test changes to this project, there should be a demo environment bundled in the repository. It doesn't need to be usable with all supported versions of Python / Django / Wagtail that this project supports, but it should at least be usable to test the following:

- StreamField Block, as documented in the README. There are no unit tests for this at the moment, and it's probably easier to test manually anyway.
- Chooser modal. This would also be easier to test manually.

This could also be useful for people to understand how they are meant to integrate this into their project (#44), as the documentation (README) is quite succinct.

**Comment by thenewguy** [comment]
fixed by commit bdc554fda8787902c5d1182569e75b3bb9d8f89d
