### ISSUE TITLE
Collections filtering needs a message for the "empty state"

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/wagtailmedia#49]
When using the collections filter in the chooser modal, if no items match the chosen collection, the UI displays `Sorry, no media files match "None"`. I imagine this is because this code is repurposed from the search results view, but it doesn't feel appropriate in this case.

<img width="689" alt="collections-filter" src="https://user-images.githubusercontent.com/877585/57378025-c1fd8e00-719b-11e9-9764-865db3863a80.png">

**Comment by zerolab** [comment]
This was fixed as a side-effect of #139
