### ISSUE TITLE
Media summary item should not be displayed if the user has no media permissions

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/wagtailmedia#50]
Spotted from #38. In the media summary item declaration, there is no permission check. This is implemented correctly for the "Media" menu item, and "Media" section of the whole-site search view. There should be a similar check for the summary block on the dashboard.

Corresponding code:

https://github.com/torchbox/wagtailmedia/blob/10dc431d18ec2a9d5310cacc25cf799ca7c4526e/wagtailmedia/wagtail_hooks.py#L55-L67

Here is the implementation from #38 for reference:

```diff
class MediaSummaryItem(SummaryItem):
    order = 300
    template = 'wagtailmedia/homepage/site_summary_media.html'
    def get_context(self):
        return {
            'total_media': get_media_model().objects.count(),
        }

+    #This was also added to only show media that user can modify.
+    def is_shown(self):
+        return permission_policy.user_has_any_permission(
+            self.request.user, ['add', 'change', 'delete']
+        )
```

**Comment by vinodMS** [comment]
Is there an alternative solution to hide the media panel from the admin home until the fix is released?

**Comment by thibaudcolas** [comment]
@vinodMS I could think of two different ways, although I haven’t tried:

- Using the [`construct_homepage_summary_items `](https://docs.wagtail.io/en/v2.6.1/reference/hooks.html#construct-homepage-summary-items) hook to remove the summary panel (https://github.com/torchbox/wagtailmedia/blob/4cfecb7a941b29cbf74be903d7bd7afd668e167f/wagtailmedia/wagtail_hooks.py#L55-L67)
- Or overriding the template, https://github.com/torchbox/wagtailmedia/blob/master/wagtailmedia/templates/wagtailmedia/homepage/site_summary_media.html

Although if you’re needing this it might be just as fast for you to implement what I’ve suggested above, make a pull request, and I’ll be happy to review it and make a new release.

**Comment by thibaudcolas** [comment]
This is tagged `help wanted` so looking for someone to pick this up if anyone is interested. I’m happy to review any PR following the implementation I outlined in https://github.com/torchbox/wagtailmedia/issues/50#issue-441739099 (including tests).

**Comment by vinodMS** [comment]
@thibaudcolas happy to take this one.

**Comment by thibaudcolas** [comment]
Great, go for it!
