### ISSUE TITLE
Add post_delete signal handler to clean up media files when deleting media instance

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/wagtailmedia#51]
Spotted from #38. Currently, deleting a media instance in the admin does not delete the corresponding file. Wagtail correctly implements this for images and documents – I think it would be fair to expect `wagtailmedia` to do this as well.

Here is the corresponding code for documents in Wagtail: https://github.com/wagtail/wagtail/blob/84072452077f229e92defd5c411ca3254e7a049a/wagtail/documents/signal_handlers.py#L1-L15

And for this module from #38:

```python
# apps.py
from django.apps import AppConfig
from django.utils.translation import gettext_lazy as _


class WagtailMediaAppConfig(AppConfig):
    name = 'wagtailmedia'
    label = 'wagtailmedia'
    verbose_name = "Wagtail media"
    verbose_name = _("Wagtail media")

    def ready(self):
        from wagtailmedia.signal_handlers import register_signal_handlers
        register_signal_handlers()
```

```python
# signal_handlers.py
from django.conf import settings
from django.db import transaction
from django.db.models.signals import post_delete, pre_save

from wagtailmedia.models import get_media_model


def post_delete_file_cleanup(instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    transaction.on_commit(lambda: instance.file.delete(False))


def register_signal_handlers():
    Media = get_media_model()
    post_delete.connect(post_delete_file_cleanup, sender=Media)
```

**Comment by gasman** [comment]
For clarity - models.py does include a signal handler for this, but it's only registered for the default `wagtailmedia.Media` model and doesn't work when a custom model is in use:

https://github.com/torchbox/wagtailmedia/blob/8dce6b67205157ecb5c69cd9da75b3afe186b38d/wagtailmedia/models.py#L154-L159

This should be removed when the above code is added.
