### ISSUE TITLE
Media Chooser not Appearing 

### ISSUE THREAD

**Issue by Aesirry** [torchbox/wagtailmedia#54]
When Using the BaseMediaChooserPanel as mentioned in #53 the chooser doesn't open when clicking on the "choose a media item" button in the edit page.

The browser console shows this error:
![image](https://user-images.githubusercontent.com/14979915/57446948-770d7480-7288-11e9-8332-584945341418.png)

**Comment by thibaudcolas** [comment]
Hey @Aesirry, thanks for the report. I imagine you'd have encountered that when trying to upgrade to the latest version, but it might be useful to get this confirmed. Could you provide the following info:

* Python version: Run `python --version`.
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
* Wagtail version: Hover over the Wagtail bird in the admin, or run `pip show wagtail | grep Version:`.
* `wagtailmedia` version: Look in your requirements.txt, or run `pip show wagtailmedia | grep Version`.

Additionally, could you provide us with a sample of the code where you use `BaseMediaChooserPanel`?

**Comment by Aesirry** [comment]
Hi @thibaudcolas, 

* Python 3.7.2
* Django 2.2.1
* Wagtail 2.5.1
* WagtailMedia 0.3.0

Here is where I use the Base MediaChooserPanel:

```python
class VideoPage(Page):
    author = models.CharField(max_length=255)
    date = models.DateField("Post date")
    body = models.TextField(blank=False)
    media = models.ForeignKey(
        get_media_model_string(),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    content_panels = Page.content_panels + [
        FieldPanel('author'),
        FieldPanel('date'),
        FieldPanel('body'),
        BaseMediaChooserPanel('media')
    ]
```
I'm using a custom media model by the way. That's where that ` get_media_model_string()` comes from.

**Comment by thibaudcolas** [comment]
👌 thanks, that will make troubleshooting much easier.

In the meantime you might be able to do what my project does, although I'm not sure of the implications:

```python
from wagtailmedia.widgets import AdminMediaChooser

[...]

content_panels = Page.content_panels + [
        [...]
        FieldPanel('media', widget=AdminMediaChooser),
    ]
```

**Comment by Aesirry** [comment]
Hey @thibaudcolas, using `AdminMediaChooser` still gives the same error. 

I guess for now just using FieldPanel should be enough. 

Thank you!

**Comment by thibaudcolas** [comment]
Ah that's really strange 😕 are you sure this isn't just a caching issue with a CDN / the browser?

I'll try both options and report back.

**Comment by Aesirry** [comment]
hmm not sure it's a CDN issue since it's on localhost, I'll check the browser

**Comment by zerolab** [comment]
The fix from #34 is on the right path

`MediaChooserPanel` needs to be:

```python
class MediaChooserPanel(BaseChooserPanel):
    object_type_name = 'media'

    def widget_overrides(self):
        return {self.field_name: AdminMediaChooser}
```

The one thing missing from that PR is a shim or deprecation for `BaseMediaChooserPanel` for projects that currently use it. Unless we cut a new release with the appropriate upgrade considerations @thibaudcolas 

Context: [Slack #support reply](https://wagtailcms.slack.com/archives/C81FGJR2S/p1557432978227700). Diff for mentioned repo:

https://github.com/torchbox/wagtailmedia/compare/master...solarissmoke:wagtail25#diff-7bea8da4a64ce9c5452abd60428fa2c9R8

**Comment by thibaudcolas** [comment]
@Aesirry also try to run `collectstatic` on your local environment to make sure this isn't the issue. We did move lots of JS code around as part of the 0.3.0 compatibility changes.

**Comment by Aesirry** [comment]
@thibaudcolas I tried creating a brand new site (the previous one had many modifications, including templates). There is another error when I try to use a RichTextField and a media field with the `AdminMediaChooser`.

![image](https://user-images.githubusercontent.com/14979915/57520894-6543d400-7351-11e9-8d36-b9798e88a4c8.png)

Again for this site the versions are the same:
* python 3.7.2
* django 2.2.1
* wagtail 2.5.1
* wagtailmedia 0.3.0

here's the model:

```python
class HomePage(Page):
    author = models.CharField(max_length=255, blank=True, null=True)
    date = models.DateField("Post date", blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    media = models.ForeignKey(
        'wagtailmedia.Media',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    content_panels = Page.content_panels + [
        FieldPanel('author'),
        FieldPanel('date'),
        FieldPanel('body'),
        FieldPanel('media', widget=AdminMediaChooser),
    ]
```

I made another model without a `media` field and the RichTextField works normally.
here's the code for that:

```py 
class RandomPage(Page):
    author = models.CharField(max_length=255, blank=True, null=True)
    date = models.DateField("Post date", blank=True, null=True)
    body = RichTextField(blank=True, null=True)

    content_panels = Page.content_panels + [
        FieldPanel('author'),
        FieldPanel('date'),
        FieldPanel('body')
    ]
```

I hope this can give you a hint in the right direction 👍

**Comment by Aesirry** [comment]
@thibaudcolas I spoke over slack with the Wagtail support and it turns out that this is actually an issue with wagtail.
![image](https://user-images.githubusercontent.com/14979915/57615517-763d5100-75ae-11e9-9533-7fdbd37ca6d6.png)
So don't name your fields "Media"!!

Also using `FieldPanel('media', widget=AdminMediaChooser)` works fine now.

**Comment by thibaudcolas** [comment]
Ah 🙂that's an annoying name clash, but I'm glad we know the solution.

👍 I'll leave this open until we do the docs change similarly to #34 / #40, and also have a note about the potential name clash to avoid.

**Comment by thibaudcolas** [comment]
I've updated the docs as part of #57, sorry you ran into @Aesirry.
