### ISSUE TITLE
Remove deprecated BaseMediaChooserPanel API

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/wagtailmedia#59]
As part of #40 / #58, we've deprecated the undocumented `BaseMediaChooserPanel`, since it's no longer needed to use it (use `AdminMediaChooser` instead). We should completely remove this API in a future release (0.4.0?).

Code to remove:

https://github.com/torchbox/wagtailmedia/blob/54c797de9243309f72e7b78d91dafde15634ba33/wagtailmedia/edit_handlers.py#L8-L16

**Comment by johnfraney** [comment]
@thibaudcolas Would it make sense to leverage this package to address this issue?

https://github.com/gasman/wagtail-generic-chooser

**Comment by thibaudcolas** [comment]
Yes, that’s very relevant to wagtailmedia 🙂 I would expect it’ll be a no-brainer to switch to using that package once it’s more established.

…but this one particular issue is just about removing `BaseMediaChooserPanel`, which I’d consider to be dead code more than anything 😬
