### ISSUE TITLE
Feature request: Add a 'construct_media_chooser_queryset' hook

### ISSUE THREAD

**Issue by juan0tron** [torchbox/wagtailmedia#72]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Wagtail provides hooks for filtering the chooser querysets for Documents, Images, and Pages:

https://docs.wagtail.io/en/v2.7/reference/hooks.html#construct-page-chooser-queryset

I would like to be able to do the same for media files.

### Current Workaround

For now, I've overridden `/templates/wagtailmedia/media/list.html` and used a template tag to pull in my filtered list.

```
# In my /templatetags/media_tags.py 

# Get a user's media filtered by their permissions
@register.simple_tag(takes_context=True)
def user_media_files(context):
	return get_user_media(context['request'].user)

# At the top of list.html 

{% user_media_files as media_files %}

```

**Comment by thibaudcolas** [comment]
Hi @juan0tron – thank you for the detailed report. This seems perfectly sensible to me – I think this library’s philosophy could be summed up as "offer what Wagtail offers for images and documents, but for video/audio".

I see PR #60 seems to be implementing exactly this – if you haven’t seen it already have you had a look at it? I’m not feeling super competent to review it so if you have the chance to spend some time reviewing that PR yourself that would definitely help.

**Comment by juan0tron** [comment]
Hey @thibaudcolas, thanks for the response! Sorry for the delay - I'll give that PR a look when I get some time later this week. :)

**Comment by zerolab** [comment]
Somehow missed that PR, now merged to master
