### ISSUE TITLE
Usage of wagtail.wagtailadmin.taggable in models is deprecated

### ISSUE THREAD

**Issue by MechanisM** [torchbox/wagtailmedia#8]
In `wagtail` from `pypi` I get deprecation warning for `wagtail.wagtailadmin.taggable`,
and `wagtail` from master says: `No module named 'wagtail.wagtailadmin.taggable'`
But there's still usages `wagtail.wagtailadmin.taggable` in models.py

**Comment by MechanisM** [comment]
Should be:

```python
    search_fields = CollectionMember.search_fields + [
        index.SearchField('title', partial_match=True, boost=10),
        index.RelatedFields('tags', [
            index.SearchField('name', partial_match=True, boost=10),
        ]),
        index.FilterField('uploaded_by_user'),
    ]
```
and subclass from `class AbstractMedia(CollectionMember, index.Indexed, models.Model):`
Just like in `wagtail.wagtaildocs`.

**Comment by rosscdh** [comment]
+1 encountered upgrading from 1.7 to 1.8

```
media_manager/lib/python2.7/site-packages/wagtailmedia/models.py", line 16, in <module>
    from wagtail.wagtailadmin.taggable import TagSearchable
ImportError: No module named taggable
```

**Comment by rosscdh** [comment]
thanks! great work.. loving wagtail so far.
