### ISSUE TITLE
Drop python 2 support

### ISSUE THREAD

**Issue by saemideluxe** [torchbox/wagtailmedia#87]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Python 2 support creates an error because wagtail 2.8 adds support for django 3 and django 3 drops support for python 2.

See https://github.com/torchbox/wagtailmedia/blob/12b94f0d99f9449fb8b628b860c75ca1fac3a909/wagtailmedia/models.py#L32
and
https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

### Steps to Reproduce

1. Start a new project with django 3 and wagtail 2.8
2. Add wagtailmedia and try to migrate

### Technical details

* Python version: 3.7
* Django version: 3.0
* Wagtail version: 2.8
* `wagtailmedia` version: master from git

**Comment by thibaudcolas** [comment]
Hi @saemideluxe, I believe this was addressed by #88, which @zerolab released yesterday as https://pypi.org/project/wagtailmedia/0.5.0/. Could you try this?

As @zerolab mentions we probably want to fully remove any Python 2 compatibility code / things that were done with compatibility in mind. According to our support targets (Wagtail 2.2) we can write Python 3.4+ code.

I’ll keep this issue open to keep track of this cleanup / optimisation work.

**Comment by saemideluxe** [comment]
@thibaudcolas great news, thanks. New we can migrate to wagtial 2.8.
For me the main issue is resolved since we can run this now under python 3 with django 3. But sure, let's track remaining python 2 issues here.
