### ISSUE TITLE
Unaccessible media referenced on admin home

### ISSUE THREAD

**Issue by michela** [torchbox/wagtailmedia#99]
### Issue Summary

Unlike image and documents unaccessible to the current user, the "# Media Files" shows the number of media files available under root. Clicking on this results in "Sorry, you do not have permission to access this area." so would be good if "# Media Files" did not appear at all. This would harmonize with core UX.

### Steps to Reproduce

1. Create user with access to no media (all media in unaccessible collection)
2. Go to /admin

**Comment by thibaudcolas** [comment]
Hey @michela, I believe this is the same issue as #50 so will close in favour of the existing one. Please let me know if this is a mistake.
